# Generated by Django 5.1.3 on 2024-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
